services:
  db:
    image: postgres:16
    container_name: em-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: em_user
      POSTGRES_PASSWORD: em_pass
      POSTGRES_DB: em_db
    ports:
      - "5432:5432"
    volumes:
      - em_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U em_user -d em_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: em-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  em_pgdata: